package acme.policyquote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class driver implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "age")
   private java.lang.Integer age;
   @org.kie.api.definition.type.Label(value = "Credit Score")
   private java.lang.Integer creditscore;
   @org.kie.api.definition.type.Label(value = "DL Number")
   private java.lang.String dlNumber;
   @org.kie.api.definition.type.Label(value = "Driver Name")
   private java.lang.String drivername;
   @org.kie.api.definition.type.Label(value = "Number of Accidents")
   private java.lang.Integer numOfAccidents;
   @org.kie.api.definition.type.Label(value = "Number of Tickets")
   private java.lang.Integer numofTickets;
   @org.kie.api.definition.type.Label(value = "SSN")
   private java.lang.String ssn;

   public driver()
   {
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.Integer getCreditscore()
   {
      return this.creditscore;
   }

   public void setCreditscore(java.lang.Integer creditscore)
   {
      this.creditscore = creditscore;
   }

   public java.lang.String getDlNumber()
   {
      return this.dlNumber;
   }

   public void setDlNumber(java.lang.String dlNumber)
   {
      this.dlNumber = dlNumber;
   }

   public java.lang.String getDrivername()
   {
      return this.drivername;
   }

   public void setDrivername(java.lang.String drivername)
   {
      this.drivername = drivername;
   }

   public java.lang.Integer getNumOfAccidents()
   {
      return this.numOfAccidents;
   }

   public void setNumOfAccidents(java.lang.Integer numOfAccidents)
   {
      this.numOfAccidents = numOfAccidents;
   }

   public java.lang.Integer getNumofTickets()
   {
      return this.numofTickets;
   }

   public void setNumofTickets(java.lang.Integer numofTickets)
   {
      this.numofTickets = numofTickets;
   }

   public java.lang.String getSsn()
   {
      return this.ssn;
   }

   public void setSsn(java.lang.String ssn)
   {
      this.ssn = ssn;
   }

   public driver(java.lang.Integer age, java.lang.Integer creditscore,
         java.lang.String dlNumber, java.lang.String drivername,
         java.lang.Integer numOfAccidents, java.lang.Integer numofTickets,
         java.lang.String ssn)
   {
      this.age = age;
      this.creditscore = creditscore;
      this.dlNumber = dlNumber;
      this.drivername = drivername;
      this.numOfAccidents = numOfAccidents;
      this.numofTickets = numofTickets;
      this.ssn = ssn;
   }

}