package acme.policyquote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ktestdo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String col1;
   private java.lang.String col2;

   public ktestdo()
   {
   }

   public java.lang.String getCol1()
   {
      return this.col1;
   }

   public void setCol1(java.lang.String col1)
   {
      this.col1 = col1;
   }

   public java.lang.String getCol2()
   {
      return this.col2;
   }

   public void setCol2(java.lang.String col2)
   {
      this.col2 = col2;
   }

   public ktestdo(java.lang.String col1, java.lang.String col2)
   {
      this.col1 = col1;
      this.col2 = col2;
   }

}