package acme.policyquote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class policy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Driver")
   private acme.policyquote.driver driver;
   @org.kie.api.definition.type.Label(value = "Policy type")
   private java.lang.String policytype;
   private java.lang.Integer price;
   @org.kie.api.definition.type.Label(value = "Price Discount")
   private java.lang.Integer pricediscount;
   private java.util.Date requestdate;
   private java.lang.Integer vehicleyear;

   public policy()
   {
   }

   public acme.policyquote.driver getDriver()
   {
      return this.driver;
   }

   public void setDriver(acme.policyquote.driver driver)
   {
      this.driver = driver;
   }

   public java.lang.String getPolicytype()
   {
      return this.policytype;
   }

   public void setPolicytype(java.lang.String policytype)
   {
      this.policytype = policytype;
   }

   public java.lang.Integer getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Integer price)
   {
      this.price = price;
   }

   public java.lang.Integer getPricediscount()
   {
      return this.pricediscount;
   }

   public void setPricediscount(java.lang.Integer pricediscount)
   {
      this.pricediscount = pricediscount;
   }

   public java.util.Date getRequestdate()
   {
      return this.requestdate;
   }

   public void setRequestdate(java.util.Date requestdate)
   {
      this.requestdate = requestdate;
   }

   public java.lang.Integer getVehicleyear()
   {
      return this.vehicleyear;
   }

   public void setVehicleyear(java.lang.Integer vehicleyear)
   {
      this.vehicleyear = vehicleyear;
   }

   public policy(acme.policyquote.driver driver, java.lang.String policytype,
         java.lang.Integer price, java.lang.Integer pricediscount,
         java.util.Date requestdate, java.lang.Integer vehicleyear)
   {
      this.driver = driver;
      this.policytype = policytype;
      this.price = price;
      this.pricediscount = pricediscount;
      this.requestdate = requestdate;
      this.vehicleyear = vehicleyear;
   }

}